### ISSUE TITLE
`LowerTriangularMatrix` for spectral coefficients

### ISSUE THREAD

**Issue by milankl** [milankl/SpeedyWeather.jl#111]
#110 explores a custom matrix format that only stores the lower triangle of coefficient matrices explicitly. Idea is that many operations just loop over `m = 1:mmax+1, l=m:lmax+1`, which technically jumps over the explicitly stored zeros in the upper triangle with `Matrix`. A `LowerTriangularMatrix` allows for access like `[i,j]` still, which needs to be translated to `[k]` in the underlying vector of `LowerTriangularMatrix` (and returns `zero(T)` for `j>i`).

Question remains how to best implement the `getindex` functions to avoid boundscheck (or propagate an `@inbounds`, currently this is just 
```julia
ij2k(i::Integer,j::Integer,m::Integer) = i+(j-1)*m-fibonacci(j)
Base.getindex(L::LowerTriangularMatrix,k::Integer) = getindex(@inbounds L.v[k])

function Base.getindex(L::LowerTriangularMatrix{T},i::Integer,j::Integer) where T
    @boundscheck (i > L.m || j > L.n) && throw(BoundsError(L,(i,j)))
    j > i && return zero(T)
    return getindex(L.v,ij2k(i,j,L.m))
end
```
and needs some care. Anyway, changing in `gridded!` from `alms[i,j]` to `alms[k]` (as the zero elements are never accessed anyway) this gives similar speeds at half the memory
```julia
julia> A = randn(ComplexF32,86,86);
julia> L = LowerTriangularMatrix(A);
julia> sizeof(A)/1000    # in KB
59.168
julia> sizeof(L)/1000    # in KB
29.928
julia> @btime SpeedyWeather.gridded!($map,$A,$m.geospectral.spectral_transform);
  686.543 μs (194 allocations: 12.12 KiB)

julia> @btime SpeedyWeather.gridded!($map,$L,$m.geospectral.spectral_transform);
  685.417 μs (194 allocations: 12.12 KiB)
```

For large grids a `LowerTriangularMatrix` is faster, presumably because of contiguous memory access
```julia
julia> @btime SpeedyWeather.gridded!($map,$L,$m.geospectral.spectral_transform);
  254.260 ms (1540 allocations: 112.22 KiB)

julia> @btime SpeedyWeather.gridded!($map,$A,$m.geospectral.spectral_transform);
  274.818 ms (1540 allocations: 112.22 KiB)
```

**Comment by milankl** [comment]
Boundschecks should be safe now with  [1fe8ea1](https://github.com/milankl/SpeedyWeather.jl/pull/110/commits/1fe8ea15845427fd9625739eb4e4c10f71982871), changed to
```julia
@inline function Base.getindex(L::LowerTriangularMatrix,k::Integer)
    @boundscheck 0 < k <= length(L.v) || throw(BoundsError(L,k))
    @inbounds r = L.v[k]
    return r
end

@inline function Base.getindex(L::LowerTriangularMatrix{T},i::Integer,j::Integer) where T
    @boundscheck (0 < i <= L.m && 0 < j <= L.n) || throw(BoundsError(L,(i,j)))
    j > i && return zero(T)
    k = ij2k(i,j,L.m)
    @inbounds r = L.v[k]
    return r
end
```

The first method definition allows to loop efficiently over all non-zero elements of a `LowerTriangularMatrix` which we do a lot in SpeedyWeather.jl. In the end, we'll probably rewrite `gridded!` and `spectral!` to only loop over the single index instead of `[i,j]` to benefit from the easier memory access (`[i,j]` needs to compute a fibonacci sequence to find the single index for the underlying vector)

**Comment by milankl** [comment]
with #116 `ij2k` was updated (as it wasn't actually a Fibonacci sequence 🙈) new timings without changes to `gridded!` are better, but still slower than with `Matrix`. For `[k]` this is obv unchanged.
```julia
julia> using SpeedyWeather, BenchmarkTools
julia> A = randn(ComplexF32,86,86);
julia> L = SpeedyWeather.LowerTriangularMatrix(A);
julia> p,d,m = initialize_speedy(trunc=85);
julia> map = gridded(L);
julia> @btime SpeedyWeather.gridded!($map,$L,$m.geospectral.spectral_transform);
  1.013 ms (194 allocations: 12.12 KiB)

julia> @btime SpeedyWeather.gridded!($map,$A,$m.geospectral.spectral_transform);
  729.433 μs (194 allocations: 12.12 KiB)
```
Large grids
```julia
julia> A = randn(ComplexF32,682,682);
julia> L = SpeedyWeather.LowerTriangularMatrix(A);
julia> p,d,m = initialize_speedy(trunc=682);
julia> map = gridded(L);
julia> @btime SpeedyWeather.gridded!($map,$A,$m.geospectral.spectral_transform);
  425.083 ms (1538 allocations: 96.38 KiB)

julia> @btime SpeedyWeather.gridded!($map,$L,$m.geospectral.spectral_transform);
  587.437 ms (1538 allocations: 96.38 KiB)
```
untested with `[k]` access in `gridded!`.

**Comment by maximilian-gelbrecht** [comment]
I tried pre-computing the `ij2k` and got even worse performance. I mean ultimately it can never reach the performance of the regular matrix for 2d indices, but I guess it should be a bit closer. With the 1D version it should be faster (probably with vectorizing / SIMD).
If we choose to rewrite most parts of the package with KernelAbstractions (let's discuss this next week), `gridded!` and `spectral!` (and other functions) have to rewritten anyway to form that is using 1D indices, so I am not sure if it is worth the trouble now to change them to another new version first.

**Comment by milankl** [comment]
Thanks for checking! But yeah, no, it would have surprised me if that was faster. In the end, array indexing is such a low-level function that anything unnecessary (including pulling another 64-bit integer from memory to access a 32/64-bit float) is likely a performance killer. I'm happy to transition to `LowerTriangularMatrix` for the spectral coefficients (incl the Legendre polynomials where we would actually save 2x in memory as they are so large `lmax*mmax*nlat`) and looping over `k` instead of `i,j` in performance-critical code, but I haven't done that yet for several reasons
- `A[k] != Matrix(A)[k]` with `A::LowerTriangularMatrix` although `A<:AbstractMatrix`. The former skips the zero elements, the latter includes it. We obviously want that for performance reasons, but if people (incl us) expect a matrix with matrix indexing but they get something else, this may cause problems. Using `for i in eachindex(A)` is equivalent to looping over `i,j` but `for k in 1:n*m` skips the zero-elements and even causes a BoundsError when `k > length(A.v)`
- We also need `LowerTriangularArray{T,N}`, which I suggeset to implement as a `Vector{LowerTriangularMatrix}` for `N=3`, `Matrix{LowerTriangularMatrix}` for `N=4`, etc. And then one would only need to redefine the `getindex` functions. I believe this can be efficiently implemented as `LowerTriangularArray{T,N}(...) = Array{LowerTriangularMatrix,N-2}` with special cases for `N=1` (error) and `N=2`. The indices could then be propagates as `A[i,j,l,m] -> A[l,m][i,j]`. We'd need to check whether this causes any problems when creating `view(LowerTriangularArray,...)`
- `gridded` and `spectral` (the allocating versions which I mostly use for development/testing purposes) should probably still allow for `Matrix` inputs, so ideally we would have a `LowerTriangularMatrixView(B::Matrix)` that just corrects the indices such that `gridded!` and `spectral!` (which now loop over `k`) can still be used without getting wrong results (which otherwise would be the case given point 1 ☝🏼 .

**Comment by milankl** [comment]
Having said that, I actually want to redefine the datastructure of our variables to something like
```julia
struct PrognosticVariablesLayer{T} where {T<:AbstractFloat}
    vor::LowerTriangularMatrix{Complex{T}}
    div::LowerTriangularMatrix{Complex{T}}
    ...
end

struct PrognosticVariables{T} where {T<:AbstractFloat}
     layers::Vector{PrognosticVariablesLayer{Complex{T}}}
     surface_pressure::LowerTriangularMatrix
end

n_layers(P::PrognosticVariables) = length(P.layers)
```
At the moment we are looping over the vertical dimension on every call to a function that's defined for a layer, and I'd like to move that loop further out, such that for example
```julia
function get_tendencies!(progn::PrognosticVariables,...)
    for progn_layer in progn
         get_tendencies!(progn_layer)
...
```
In that case, `LowerTriangularArray` isn't actually needed as `PrognosticVariables` effectively does that. Only the Legendre polynomials would need to be implemented as `Vector{LowerTriangularMatrix}`

**Comment by milankl** [comment]
with v0.3 (#117 merged that into main) timings are
```julia
julia> using .SpeedyWeather
julia> using BenchmarkTools
julia> A = randn(ComplexF64,87,86);
julia> L = LowerTriangularMatrix(A);
julia> p,d,m = initialize_speedy(Float64,trunc=85);
julia> map = gridded(L);
julia> @btime SpeedyWeather.gridded!($map,$L,$m.spectral_transform);
  485.377 μs (130 allocations: 10.38 KiB)
```
was 686mus with `Matrix`, and for T682
```julia
julia> @btime SpeedyWeather.gridded!($map,$L,$m.spectral_transform);
  223.318 ms (1028 allocations: 80.22 KiB)
```
was 274ms with `Matrix`. So speed gain with `LowerTriangularMatrix` is about 20-30% 🥳
