### ISSUE TITLE
A new grid for SpeedyWeather.jl?

### ISSUE THREAD

**Issue by milankl** [milankl/SpeedyWeather.jl#112]
At the moment we use a regular Gaussian grid for grid-point space. This comes with advantages of easy storage in a matrix internally and for output but with the disadvantage that a lot of points are put near the poles that aren't actually needed. Alternatives are
- a reduced Gaussian grid (https://confluence.ecmwf.int/display/FCST/Gaussian+grids)
- an octahedral Gaussian grid (https://github.com/jmert/CMB.jl/issues/71)
- a HEALPix grid (https://github.com/jmert/CMB.jl/pull/68, https://en.wikipedia.org/wiki/HEALPix, https://arxiv.org/pdf/astro-ph/0412607.pdf)

This is an issue to discuss and collect ideas and reasons to implement either of these grids at some point in the future.

**Comment by milankl** [comment]
Also useful https://arxiv.org/abs/astro-ph/0409513
To summarize, some of the HEALPix grid's properties
- 12 base pixels (4 diamonds centred on the equator + 4 diamonds merging at north/south pole, picture from ref above
![image](https://user-images.githubusercontent.com/25530332/182150600-ac16f3ce-e379-4c4a-9b0b-fd9a249e98e9.png)
- Choose $N_{side}$ as the parameter that effectively controls the resolution
- These base pixels are subdivided into $N_{side}^2$ pixels, such there is $12N_{side}^2$ pixels/grid points in total
- The area of each base pixel is $\Omega = 4\pi r^2/12$, the area of each grid point is $\Omega = 4\pi r^2/(12N_{side}^2)$
- Polar and equatorial zone are divided by $\cos(\theta) = 2/3$, i.e. $\pm 48.18968510422141$
- In the equatorial zone there are $4N_{side}$ grid points/pixels per latitude ring
- In the polar zones there are $4,8,12,16,20,...,4N_{side}$ pixels per latitude ring

We can create a dependency on [Healpix.jl](https://github.com/ziotom78/Healpix.jl) and use their functions and the data structure
```julia
Nside = 64
H = HealpixMap{Float32,RingOrder}(Nside)
```
to hold the data in grid point space. We could use the following resolutions 

| spectral | $N_{side}$ | $N_{lon}$ | $N_{lat}$ | $N_{pix}^H = 12N_{side}^2$ | Gaussian grid: $N_{lat}$ | $N_{pix}^G = N_{lon}N_{lat}$ |
| - | - | - | - | - | - | - |
| T21 | 16 | 64 | 63 | 3072 | 32 | 2048 |
| T31 |   |   |   |   | 48 | 4608 |
| T42 | 32 | 128 | 127 | 12288 | 64 | 8192 |
| T85 | 64 | 256 | 255 | 49152 | 128 | 32768 |
| T170 | 128 | 512 | 511 | 196608 | 256 | 131072 |
| T341 | 256 | 1024 | 341 | 786432 | 512 | 524288 |
| T682 | 512 | 2048 | 681 | 3145728 | 1024 | 2097152 |

**Comment by milankl** [comment]
In comparison the number of total grid points $N_{pix}^O$ for the octahedral grid 
| spectral | $N_{lon}$ (Eq) | $N_{pix}^G$ | $N_{pix}^H$ | $N_{pix}^O$ |
| - | -:| -:| -:| -:|
| T21 | 64 | 2048 | 3072 (x1.5) | 1600 (x0.78) |
| T31 | 96 | 4608 | | 3168 (x0.68) |
| T42 | 128 | 8192 | 12288 (x1.5) | 5248 (x0.64) |
| T85 | 256 | 32768 | 49152 (x1.5) | 18688 (x0.57) |
| T170 | 512 | 131072 | 196608 (x1.5) | 70144 (x0.54) |
| T341 | 1024 | 524288 | 786432 (x1.5) | 271360 (x0.52) |
| T682 | 2048 | 2097152 | 3145728 (x1.5) | 1067008 (x0.51) |

So the number of grid points for HEALPix is always x1.5 more than on the Gaussian grid, but the octahedral grid converges to half the Gaussian grid.

**Comment by milankl** [comment]
![grids](https://user-images.githubusercontent.com/25530332/182353748-ad1b89d8-32ea-4479-ba06-a906ed281364.png)

**Comment by milankl** [comment]
After playing around with creating different grids, I believe we'll always have the Fourier constraints that at the equator $N_{lon} \geq 2T+1$, but with the regular Gaussian grid we currently use $N_{lon} \geq 3T+1$ and in the meridional the quadrature requires $N_{lat} \geq (2T+1)/2$. Clenshaw-Curtis quadrature (needed for HEALPix) would have $N_{lat} \geq 2T+1$ instead, but I believe we could fall back to the less contraining condition in the zonal. So I believe a fair comparison would be

| $N_{side}$ | $N_{lon}$ | $N_{lat}$ | $N_{pix}^H = 12N_{side}^2$ | spectral | reg. Gaussian grid $N_{lon}$x$N_{lat}$ | $N_{pix}^G = N_{lon}N_{lat}$ |
| -:| -:| -:| -:| -:| -:| -:|
| 16 | 64 | 63 | 3072 | T31 | 96x48 | 4608 |
| 32 | 128 | 127 | 12288 | T63 | 192x96 | 18432 |
| 64 | 256 | 255 | 49152 | T127 | 384x192 | 73728 |
| 128 | 512 | 511 | 196608 | T255 | 768x384 | 294912 |
| 256 | 1024 | 1023 | 786432 | T511 | 1536x768 | 1179648 |
| 512 | 2048 | 2047 | 3145728 | T1024 | 3072x1536 | 4718592 |

Then the number of grid points for HEALPix is always 2/3 of the regular Gaussian grid.

**Comment by milankl** [comment]
Following [Hotta 2018](https://rmets.onlinelibrary.wiley.com/doi/epdf/10.1002/qj.3282) one should be able to swap out the Legendre weights we currently use with the Clenshaw-Curtis quadrature that uses the following weights

![image](https://user-images.githubusercontent.com/25530332/183068100-125042f7-687a-4795-82f5-0aec94dca8fb.png)

**Comment by milankl** [comment]
Curtis Clenshaw weights can only be applied for equi-latitude grids, or grids with imposed equi-latitude, e.g. the octahedral grid with Gaussian latitudes could be swapped for equi-distant latitudes. In any case, one can always fall back to a Riemann sum, which doesn't guarantee exactness as the Gaussian/Clenshaw-Curtis quadratures, but this might not be needed. An equi-latitude HEALPix would look like
![image](https://user-images.githubusercontent.com/25530332/183771234-524ce9d1-8683-44f3-b3cd-f98fad690557.png)
which compensates for the higher meridional density of points in the transition zone betwenn the equatorial belt and the polar caps
![image](https://user-images.githubusercontent.com/25530332/183771358-b69d78a6-8f74-45a5-aa83-7475768d5c76.png)
Riemann weights for the normal HEALPix grid would be
```julia
julia> using Healpix
julia> Nside = 16
julia> res = Healpix.Resolution(Nside)
julia> pixels_per_ring = [getringinfo(res,i).numOfPixels for i in 1:4Nside-1]
63-element Vector{Int64}:
  4
  8
 12
 16
 20
 24
  ⋮
 24
 20
 16
 12
  8
  4

julia> weights = 2pixels_per_ring/12Nside^2
63-element Vector{Float64}:
 0.0026041666666666665
 0.005208333333333333
 0.0078125
 0.010416666666666666
 0.013020833333333334
 0.015625
 ⋮
 0.015625
 0.013020833333333334
 0.010416666666666666
 0.0078125
 0.005208333333333333
 0.0026041666666666665

julia> sum(weights)
2.0
```

**Comment by milankl** [comment]
Started the implementation in #122

**Comment by milankl** [comment]
#124 implements further grid abstractions towards a single spectral transform that can support all of the grids discussed above

**Comment by milankl** [comment]
Daisuke Hotta @hottad was proposing HEALPix4x1 grid, that uses 4 base pixels, no equatorial zone, from Gorski's paper the pixel positions then become
$$z = 1 - \frac{i^2}{N_{side}^2}$$
with ring index $1 \leq i \leq N_{side}$ (northern hemisphere + equator)
$$\phi = \frac{\pi}{2i}(j-\frac{1}{2})$$
with pixel-in-ring index $1 \leq j \leq 4i$. So just the $1/3$ is dropped from Gorski eq. (4) and (5). Similarly the boundaries (eq. (19) and (20)) drop the $1/3$ factor and extend all the way to the equator, $z > 0$. This yields the HEALPix4 grid which looks like

![image](https://user-images.githubusercontent.com/25530332/185425960-6aa44ede-fc78-4440-a97a-2428b6d331f2.png)

It has at most $4N_{side}$ longitude points around the equator, $2N_{side}-1$ latitude rings and $4N_{side}^2$ grid points in total. It may be more attractive for our purposes as it retains a 2:1 ratio of maximum points around the equator over latitude rings. Therefore cubic in latitude is also cubic in longitude. A cubic truncation with T31 could be H32 (HEALPix4 with $N_{side}=32$ which has 63 latitude rings, at most 128 longitudes and 4096 points in total, which is exactly half of what a full Gaussian grid would have with cubic truncation (8192 points) and less than an octahedral grid (5248).

**Comment by milankl** [comment]
Summing this up, I think if we want cubic truncation with T31 then these would be good alternative candidates, F32 (128x64 grid points) the current default but higher resolution for cubic, O32 (64 latitude rings, 144 longitude points around the equator), H32 (63 latitude rings, 128 points around the equator)

![image](https://user-images.githubusercontent.com/25530332/185432370-cd9a8a92-8700-40a9-92f2-10c70884d47c.png)

Cool thing is, H32 would have even fewer grid points than F24 what we currently use for T31. In terms of the FFT complexity, which is $n\log(n)$, we currently have with F24 $mn \log(n) = 48*96\log{96} = 21033$ whereas H32 would have $2\sum_{i=1:32} 4i \log(4i) = 18541$ so about 15% lower. In essence, we may get cubic truncation, speed and equal area all at once!

**Comment by milankl** [comment]
We could also, without any interpolation needed, store the data on a HEALPix4 grid directly ncview-able into a square matrix like so
![image](https://user-images.githubusercontent.com/25530332/185442641-0e0ea361-30e4-46aa-bd29-90649444f585.png)
@samhatfield I think that would produce some funky videos, with storm tracks running diagonally across the chess board ♟️ ↗️

**Comment by milankl** [comment]
With #127 the spectral transform in T31 is timed with
```julia
for grid in (FullGaussianGrid,FullClenshawGrid,OctahedralGaussianGrid,HEALPixGrid)
   map = gridded(alms;grid)
   S = SpeedyWeather.SpectralTransform(map,recompute_legendre=false)
   @btime SpeedyWeather.gridded!($map,$alms,$S)
   @btime SpeedyWeather.spectral!($alms,$map,$S)
end
```
as (all Float64)

| Grid | truncation | gridded! | spectral! |
| :---  | :---            | -------:  | -------:   |
| FullGaussianGrid | F32 cubic | 40.226 μs | 40.598 μs |
| FullClenshawGrid | C32 cubic | 42.538 μs | 39.962 μs |
| OctahedralGaussianGrid | O32 cubic | 51.178 μs | 43.962 μs |
| HEALPixGrid | H16 cubic-lat | 32.755 μs | 34.196 μs |

Note that the new grids are compared to F32 (so the current non-default cubic version of linear F24 we normally use with T31). HEALPix is only cubic in latitude, but linear in longitude. But sanity check: A single spectral transform can be fast for a range of grids ✅

**Comment by hottad** [comment]
Great!
I suppose you implemented the regular HEALPix (with 12 base pixels).
With #127, has it become mature enough to allow experimenting with various other grid possibilities? If so, I'd be happy to try HEALPix4 and other things.

**Comment by milankl** [comment]
just a little overview about the characteristics of the latitudinal resolution of the different grids / quadratures with 1024 latitude rings (Gaussian) or 1023 (Clenshaw-Curtis, HEALPix).

- Gaussian latitudes / Clenshaw-Curtis are practically / exactly equi-spaced
- The standard HEALPix grid (4x3 = 12 basepixels) has a higher meridional resolution around the Equator, and lower at mid-latitudes
- Vice versa for the HEALPix4 grid (4x1 = 4 basepixels)
- Both HEALPix grids compensate that with a respectively higher/lower resolution in the zonal direction because they are equal-area.

![lat_resolution](https://user-images.githubusercontent.com/25530332/186689440-c1dbd045-1949-408b-9b76-0fca378afe9b.png)

**Comment by milankl** [comment]
Looping over rings was changed with #132
