### ISSUE TITLE
copyto! function of LowerTriangularMatrix 

### ISSUE THREAD

**Issue by maximilian-gelbrecht** [milankl/SpeedyWeather.jl#165]
Is it intended that both 

https://github.com/milankl/SpeedyWeather.jl/blob/74b3a83eb7460cedec529990710e0c25abaea5c9/src/lower_triangular_matrix.jl#L187-L205

https://github.com/milankl/SpeedyWeather.jl/blob/74b3a83eb7460cedec529990710e0c25abaea5c9/src/lower_triangular_matrix.jl#L171-L185

return `L`? One should return `M`, no?

**Comment by milankl** [comment]
Yes, `copyto!(M::AbstractMatrix,L::LowerTriangularMatrix)` should return `M` clearly...

**Comment by maximilian-gelbrecht** [comment]
I'll fix that in the PR
