### ISSUE TITLE
Variable initialisation

### ISSUE THREAD

**Issue by dmey** [milankl/SpeedyWeather.jl#170]
Variables (e.g. `column_variables.jl`) are initialised with zero. Is there any reason for doing so? If not why not using `NaN` for floats and `typemax` or `typemin` for ints?

**Comment by milankl** [comment]
Does it matter, it will be overwritten anyway? To initialise arrays as with NaNs we would need to do
```julia
julia> fill(convert(NF,NaN),2,3)
2×3 Matrix{Float16}:
 NaN  NaN  NaN
 NaN  NaN  NaN
```
for example, such that for ever `NF<:AbstractFloat` there needs to a conversion from NaN to whatever NaN corresponds to in NF.

**Comment by milankl** [comment]
No it's not a performance issue. In both cases memory is allocated and filled with bits. Doesn't matter what those are.
```julia
julia> using BenchmarkTools
julia> c = NaN
julia> @btime fill($c,1000,1000);
  1.160 ms (2 allocations: 7.63 MiB)

julia> c = 0.0
julia> @btime fill($c,1000,1000);
  1.163 ms (2 allocations: 7.63 MiB)
```
Note that in the dynamics we allocate with zeros, and I never had a debugging-related issue with this. Happy for you to convert the initialisation for ColumnVariables to init with NaN, if people prefer that. I would suggest to define
```julia
function nans(::Type{T},dims...) where T
     return fill(convert(T,NaN),dims...)
end
```
in utility_functions.jl such that `zeros(NF,...)` works as `nans(NF,...)`
```julia
julia> nans(Float16,2)
2-element Vector{Float16}:
 NaN
 NaN

julia> nans(Float32,2)
2-element Vector{Float32}:
 NaN
 NaN
```

**Comment by milankl** [comment]
`nans` has been added now ☝🏼
