### ISSUE TITLE
Use PsychroLib for psychrometric calculations

### ISSUE THREAD

**Issue by dmey** [milankl/SpeedyWeather.jl#172]
This is kind of a placeholder but maybe we should consider using https://github.com/psychrometrics/psychrolib for psychometric calculations as it may come in handy later with some parametizations like land and diagnostics. Let me know if this could be useful in the future as will need to port it to Julia...

**Comment by milankl** [comment]
Thanks for raising this. I believe there's also Thermodynamics.jl which probably has a similar focus? I don't know how much or how little overlap there is to over CliMA packages. In general, at the moment I think we can go relatively lightweight unless there's something harder to implement which we'd like to outsource to another (possibly existing) package.

**Comment by milankl** [comment]
Perfect, if you feel anything should be taken via dependency on another package feel free to reopen this issue
