### ISSUE TITLE
Factory Methods for Testing

### ISSUE THREAD

**Issue by white-alistair** [milankl/SpeedyWeather.jl#84]
For testing, it would be useful to have lightweight and minimal factory methods in the `test` directory which return a model initialised with realistic values (possibly from a previous run of the model), so you can just do, for example,

```julia
prog, diag, model = model_factory()
```

or

```julia
diag = diag_factory()
```

Much of this already exists, e.g. the `initialize_from_rest` method in `prognostic_variables.jl`, but it would be good to extend and formalise it.

**Comment by milankl** [comment]
We already export initialize_speedy() that does that (takes the same arguments as run_speedy)

**Comment by milankl** [comment]
Closing this as I believe `initialize_speedy` addresses that, feel free to reopen if that remains an issue.
