### ISSUE TITLE
Pre-allocate grid-point pressure values and use consistent naming

### ISSUE THREAD

**Issue by white-alistair** [milankl/SpeedyWeather.jl#91]
This is a left over from [this comment](https://github.com/milankl/SpeedyWeather.jl/pull/82#discussion_r885489677) on #82

**Comment by milankl** [comment]
On this note, for the shallow water model, I've decided to use the interface displacement η as prognostic variable, so the instantaneous layer thickness h = η + H, whereby H is the thickness at rest and H = H₀ - orography and H₀ a global constant, something like 8-12km probably. Having said that, I don't want to redefine the variable names in `PrognosticVariables` for the different models, so I'll be using `pres` (or even `pres_log` if we decide to redefine it) for η. This is probably an argument to keep this variable name quite generic (I vote for `pres`, as this has a generic meaning, whether you think about logarithm of surface pressure or interface displacement).

**Comment by white-alistair** [comment]
@milankl picking this up again. How about the following approach:

1. Pre-allocate a new grid variable `pres_exp_grid` in the `GridVariables` struct (the name is potentially misleading, but I think all of the options are suboptimal in their own way, so I'd be happy to go with your preference from the previous comment).
2. In `tendencies_parametrizations.jl`, do `pres_exp_grid = exp.(pres_grid)`, i.e. before any of the parametrizations are calculated, since this quantity is used by several of them. I'm not 100% this is the most logical place to do this, but as far as I know we only use this in the parametrizations.

Let me know what you think!

**Comment by milankl** [comment]
Is `pres_grid` (i.e. the logarithm of surface pressure on the grid) even used for the tendencies? If not, we could just have `pres_grid` which is first transformed from spectral `pres` and then calculate the exponent in-place? Then `pres` would always be the logarithm of surface pressure in spectral space and `pres_grid` the surface pressure (hPa) in grid-point space.

**Comment by white-alistair** [comment]
As far as I can see it's only used for the physics, so yeah I think this works. I'll just comment it clearly so newcomers aren't confused :)
